# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely edit after that. If you find
# yourself editing this file very often, consider using Jekyll's data files
# feature for the data you need to update frequently.
#
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'bundle exec jekyll serve'. If you change this file, please restart the server process.
#
# If you need help with YAML syntax, here are some quick references for you:
# https://learn-the-web.algonquindesign.ca/topics/markdown-yaml-cheat-sheet/#yaml
# https://learnxinyminutes.com/docs/yaml/
#
# Site settings
# These are used to personalize your new site. If you look in the HTML files,
# you will see them accessed via {{ site.title }}, {{ site.email }}, and so on.
# You can create any custom variable you would like, and they will be accessible
# in the templates via {{ site.myvariable }}.

title: Silicon Valley Woodworker
subtitle: Learn woodworking the casual way
email: hi@svwoodworker.com
description: >- # this means to ignore newlines until "baseurl:"
  An aspiring woodworker located in Silicon Valley. Join me and start your journey today.
baseurl: "" # the subpath of your site, e.g. /blog
url: "https://www.svwoodworker.com" # the base hostname & protocol for your site, e.g. http://example.com
# name: Silicon Valley Woodworker
teaser: /assets/uploads/teaser.jpg

author:
  display_name:
  home: /about/
  location: San Francisco, CA
  avatar: /logo-800.jpg
  bio: Weekday engineer, weekend warrior.
  links: &social-links
    - label: "YouTube"
      icon: "fab fa-fw fa-youtube"
      url: "https://www.youtube.com/channel/UCUedAzXRC_IEixNdYh6PX0w"

footer:
  links: *social-links

# theme: jekyll-theme-midnight
# remote_theme: pages-themes/midnight@v0.2.0
theme: minimal-mistakes-jekyll

# Build settings
plugins:
  - jekyll-feed
  - jekyll-relative-links
  - jekyll-paginate
  - jekyll-seo-tag
  - jekyll-include-cache
  - jekyll-archives
  - jekyll-cloudinary
  - jekyll-remote-theme # add this line to the plugins list if you already have one

logo: "logo.png"
minimal_mistakes_skin: default
read_time: true

paginate: 5  # amount of posts to show per page
paginate_path: /page:num/

search: true
search_full_content: true

# Taxonomy pages
category_archive_path: "/categories/#"
tag_archive_path: "/tags/#"

comments:
  provider: disqus
  disqus:
    shortname: svww # use JEKYLL_ENV=production to actually see it locally

# specify default post Front Matters
defaults:
  # _posts
  - scope:
      path: ""
      type: posts
    values: &posts_default_value
      layout: single
      toc: true
      author_profile: true
      read_time: true
      comments: true
      share: true
      related: true
      show_date: true
  # _drafts
  - scope:
      path: ""
      type: drafts
    values: *posts_default_value
  # _pages
  - scope:
      path: ""
      type: pages
    values:
      layout: single

# use jekyll-archives for archives
category_archive:
  type: jekyll-archives
  path: /categories/
tag_archive:
  type: jekyll-archives
  path: /tags/
jekyll-archives:
  enabled:
    - categories
    - tags
  layouts:
    category: archive-taxonomy
    tag: archive-taxonomy
  permalinks:
    category: /categories/:name/
    tag: /tags/:name/

# default image displayed in Open Graph, e.g.,
og_image: /assets/upload/logo.png

# Exclude from processing.
# The following items will not be processed, by default.
# Any item listed under the `exclude:` key here will be automatically added to
# the internal "default list".
#
# Excluded items can be processed by explicitly listing the directories or
# their entries' file path in the `include:` list.
#
# exclude:
#   - .sass-cache/
#   - .jekyll-cache/
#   - gemfiles/
#   - Gemfile
#   - Gemfile.lock
#   - node_modules/
#   - vendor/bundle/
#   - vendor/cache/
#   - vendor/gems/
#   - vendor/ruby/

# These are my customized flags
excerpt_length: 250
show_teaser_in_list: true

cloudinary:
  cloud_name: maomao
  verbose: true
  presets:
    default:
      min_width: 320
      max_width: 1200
      fallback_max_width: 800
      steps: 5
      sizes: '(min-width: 50rem) 50rem, 90vw'
      figure: always

# for google analytics
analytics:
  provider: "google-gtag"
  google:
    tracking_id: "G-HGBGBVGW2L"
    anonymize_ip: false # default
